import sys

BAD_POSITIONS = {"Admin","admin","Worker","Researcher","RA","Spec","Temporary","Doctoral","Suppmental","Cook","Practical","Attendant","Intern","Developer","Info Tech Mgmt 3",
"Assistant Child Care Teacher",
"Painter",
"System Engineer",
"Animal Care Manager 2",
"Camp Ops/Protect Prof 3 Sup",
"Data Analyst",
"Student Affairs Manager",
"Senior Energy Engineer",
"Pharmacy Associate",
"Academic Advisor",
"Finance Professional 3 Supv",
"External Service Provider",
"Business/Systems Analyst 3",
"Alumni Rel/Adv Op Ofc No Entry",
"Research Coordinator",
"Monarch Joint Venture Science",
"Education and Operations Mgr",
"Student Services Manager 2",
"Assistant Scientist",
"Printing Scheduler",
"Materials Mgmt Assistant",
"Assistant Vice President",
"Sch Building",
"Pipefitter",
"Senior Laboratory Technician",
"Psychotherapist",
"Dental Assistant",
"Summer Term TA (w/o Tuit Ben)",
"CETI Program Manager",
"Assessment Tech: N Carolina",
"Facilities Team Manager",
"Psych Clinic Rsrch Trainer",
"Non-Univ Temp/Casual Employee",
"Security Program Manager",
"Gift Officer 5b",
"Asst AD, Communications",
"Museum Preparator",
"COSP Graduate Assistant",
"Off-Cmps Study Prog Coordinatr",
"Developer",
"Mechanic 2",
"Grants/Cntrcts Prof 3",
"Finance Professional 2 Supv",
"Fullbright Scholar (affiliated)",
"Dtr, Editorial and Design Svcs",
"Junior Cashier/Food Aide",
"Visiting Scholar (affiliated)",
"Assoc AD, Health",
"Visiting PhD Student (affiliated)",
"Digital Content Strategist",
"Research Professional 2",
"Non Exempt Cas/ Cmty Prog",
"Allied Health Care Prof2 Supv",
"Pharmacy Technician",
"Purchasing Professional 3",
"Sr Veterinary Technician - ER",
"Human Resources Generalist 1",
"End User Support",
"Admissions Associate",
"Development Assistant",
"Workforce Planning",
"Allied Health Care Prof 2",
"Finance Analyst 3",
"Allied Health Care Prof3 Supv",
"AgroInform Resrcher/Data Sci",
"Asst Dir Leases",
"Comm Rel/Otrch Assoc 3 No Ent",
"Grants/Cntrcts Prof 3 No Entry",
"Access Consultant",
"Interpreter - Somali",
"Intern",
"Procurement",
"Grant Writing",
"Research Quality Analyst",
"Massage Therapist",
"Research Nurse 4 No New Entry",
"Associate Development Officer",
"CETI Process Manager",
"Professional Program Assistant",
"IMED Medical Resident",
"Career Counselor",
"Endow Prof Targeted Delivery",
"Senior Veterinary Technician",
"Nursing Assistant",
"Assistant Vice Provost",
"Donor Rel and Stewardship",
"Business/Systems Analyst 2",
"Construction Laborer",
"Education Program Manager 2",
"Student Services Prof 2",
"Dental Incentive Plan",
"Admissions Counselor",
"Non-University Employee (affiliated)",
"Mental Health Care Provider 2",
"BioNet Research Technician",
"Research Professional 4 No NE",
"Associate Academic Advisor",
"Tutor Coordinator",
"Infrastructure Analyst",
"Radiographic Tech- Temp",
"Education Program Associate 2",
"Lab Services Coordinator",
"Student Academic Support",
"Clinical Trials Assistant",
"Scientist",
"Human Resources Consultant 1",
"Info Tech Mgmt 1 No Entry",
"Mechanic 3",
"Sr Compensation Analyst",
"Coordinator",
"BHH Program Manager",
"Graduate Program Coordinator",
"Graduate Assistant Coach",
"Graphic/Multimedia Designer",
"Veterinary Technician",
"Finance Manager 2",
"Research Assoc No New Entry (affiliated)",
"Finance Professional 2",
"University Regent",
"Animal Care Provider 3",
"Manager",
"Casual Assistant",
"Medical Resident",
"IRB Analyst",
"Musician - Dance",
"End User Support 1",
"Assistant To",
"Developer 2 (affiliated)",
"Office Support Assistant",
"Plumber",
"Research Professional 4",
"Marketing Assistant",
"Research Support Manager 1",
"Non-Exempt Casual Facilitator",
"Research Professional 3",
"Senior Auditor",
"Steam/Chld Water Utilities Sup",
"Senior Academic Advisor",
"Business/Systems Analyst",
"0001 GH Res Asst",
"Data Architect",
"Camp Ops/Protect Prof 2",
"Finance Manager 1 No Entry",
"Natl Media Relations Consultan",
"Teaching Assistant",
"Sign Language Interpreter",
"Prin Graphic/Multimedia Des (affiliated)",
"Animal Diagnostic Prof 2",
"Developer 2",
"Library/Museum Manager 1",
"Pub/Int Rel Comm Sr Consultant",
"One Stop Counselor 4",
"Finance Analyst 2",
"Triage Nurse",
"Seasonal Custodial Assistants",
"Allied Health Care Provider 2",
"Finance Professional 3",
"Info Tech Mgmt 2",
"Instructional Services Librari",
"Prin Envrn Health/Safety Tech",
"Golf Course Grounds Crew",
"Dentist (affiliated)",
"Video Production Assistant",
"Community Program Assistant",
"PhD Candidate Research Asst",
"Intercollegiate Athl Equp Wrkr",
"Academic Technologist 2",
"Postgraduate Pharmacy Resident (affiliated)",
"Alumni Rel/Adv Ops Officer",
"Finance Professional 1",
"Curator",
"Financial Analyst",
"Service Learning Coordinator",
"OAP Operations/Processes Mgr",
"Human Resources Generalist 2",
"Pub/Int Rel Comm Consultant",
"Senior Cashier/Food Aide",
"Research Professional 3 Supv",
"Library Associate 2",
"Junior Scientist",
"Executive in Residence (affiliated)",
"Project Coordinator",
"Graduate School Trainee",
"Research Support Mgr 2",
"Chi Summer Intern",
"Copy Center Equipment Operator",
"Student Services Manager 3",
"Admissions Associate/Reader",
"Mechanical Engineer 1",
"Assessment Tech: Kentucky",
"Student Services Prof 3",
"Extension Program Associate 2",
"Developer 3 No Entry",
"Human Resources Generalist 3",
"Visiting Research Asst Prof (affiliated)",
"Animal Diagnostic Prof 3",
"Developer 1",
"One Stop Counselor 3",
"CORE Intern (affiliated)",
"Animal Diagnostic Prof 1",
"Finance Professional 4 Supv",
"Veterinary Medical Resident",
"Communications Associate",
"Executive Assistant",
"Summer Sess TA (w/o Tuit Ben)",
"Medical Assistant",
"Research Professional 1",
"OTC Royalty Accountant",
"Camp Ops/Protect Mgr 2",
"Graphic/Multimedia Comm Assoc",
"Mental Health Care Provider 1",
"Research Professional 4 No Ent",
"Student Services Prof 1",
"Laborer",
"Lead Accountant",
"Police Officer",
"Clinical Services Coordinator",
"Student Services Manager 1",
"Developer 3",
"PhD Candidate Teaching Asst",
"Database Technician",
"QA and Committee Assistant",
"Student Personnel Coordinator",
"Asst Prof - Will be hired 7/27 (affiliated)",
"Ext Prog Assoc 3 - No Entry",
"IATSE stage hands",
"Coordinator, AI Recruitment",
"Data Modeler / Architect",
"Technology Support Analyst",
"Ugrad Rsrch Asst(Non-Univ Stu)",
"Nursing Professional",
"Junior Laboratory Technician",
"Research Manager 2 No Entry",
"Principal Auditor",
"Research Manager 3",
"Grants/Cntrcts Prof 2",
"Camp Ops/Protect Prof 2 Sup",
"Student Finance Counselor 2",
"Principal Editor/Writer",
"Captioner",
"Summer Term AF (w/o Tuit Ben)",
"Camp Ops/Prot Mgr 2 No Entry",
"DBA Program Manager",
"Animal Care Professional 2",
"Senior Career Counselor",
"Library Assistant 2",
"Principal Engineer",
"Prin Ofc",
"Medical Student Tutor",
"Assistant Librarian",
"Animal Care Manager 3",
"IMED Chief Resident",
"Pennycress Research Manager",
"Patient Cr Provider1 No Entry",
"Librarian",
"Severance",
"End User Support 2",
"Manager, Enterprise Systems",
"Business/Systems Analyst 1",
"Concrete Finisher",
"Mental Health Care Prof 2",
"Affiliate",
"Athletics Operations Manager 3",
"Research Assistant",
"Assistant Coach",
"CURE Intern",
"Research Associate (affiliated)",
"Patient Care Professional 2",
"Legal Proj Asst (w/o Tuit Ben)",
"Athletic Trainer",
"Environmental Hlth",
"Art Museum Preparator",
"Clinical Research Coordinator",
"Student Tech Support Services",
"Grad School Committee Member (affiliated)",
"Business Development Mgr 1",
"BioStats Graduate (affiliated)",
"Admissions Interviewer",
"Library Assistant 3",
"Admissions Operations Coord",
"International Counselor (affiliated)",
"Pre K-12 Manager 2 - No Entry",
"Ops/Prot Prof Supv 4 No Entry",
"Finance Professional 4",
"Audio/Visual Media Producer",
"LPA-McGeveran",
"Sr Associate General Counsel",
"Camp Ops/Protect Prof 1",
"Communications Supv No Entry",
"Research Support Manager 3",
"Graduate Subject Tutor",
"Research Intern",
"Systems Analyst",
"Finance Supervisor 3",
"Mechanic 1",
"Senior Attorney-Sanderson"}

if (len(sys.argv) != 3) or ("-h" in sys.argv) or ("--help" in sys.argv):
    print("Usage: {} <input file> <output file>\nGenerates a list of unique positions in <input file> and outputs them in <output file>".format(sys.argv[0]))
    exit()

with open(sys.argv[1],"r") as inputfile, open(sys.argv[2],"a") as outputfile:
    for line in inputfile:
        if any([bad in line.split(",")[2] for bad in BAD_POSITIONS]):
            continue
        outputfile.write(line)
